### ISSUE TITLE
controller branch: representers/food_ranks.rb

### ISSUE THREAD

**Issue by SOA-KunLin** [NoBetterThan97/Worldca-api#5]
In https://github.com/NoBetterThan97/Worldca-api/blob/3525e9096f834b8765f1b211cf01a4c5a116b208/representers/food_ranks.rb#L6-L10 ,
You can consider using ruby json:
```
require 'json'

data = results.map do |a|
  { 
    food_id: a.food_id,
    name: a.name,
	tag_amount: a.tag_amount,
	rank: a.rank
  }
end
output = data.to_json
```

**Comment by cyhsutw** [comment]
@SOA-KunLin Thanks for reviewing, we'll take a look at it soon! 👍
